@host=http://localhost:5006

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMzhmZWJhZS1kZGM1LTQwNDEtOGUxNC1mMjEwZWNhODBlMDEiLCJnaXZlbl9uYW1lIjoiT25kcmVqIiwiZmFtaWx5X25hbWUiOiJEbGVzayIsImp0aSI6IjQ2ZDE0Mjk4LWE2NTItNGIwMy1hMzI1LWE3Yzc5MDRhM2Q3ZCIsImV4cCI6MTY4NDc2NTQ3MiwiaXNzIjoiTWVlZWUiLCJhdWQiOiJNZWVlZSJ9.ZHwIxHB1lvaCfQUX8MyYO3zIce4-DSXu8ogh8MOcFzg